### ISSUE TITLE
Error disconnects notebook from jupyter kernel when changing ImageWidget 't' slider

### ISSUE THREAD

**Issue by X4ndri** [kushalkolar/fastplotlib#183]
I've encountered this error when using ImageWidget. It occurs in response to sliding the 't' dimension slider. The slider works normally for a few seconds and the frame update, but then this error pops up on the terminal running the notebook. The notebook immediately disconnects from the kernel. The error happens in multiple environments, all running fastplotlib 0.1.0.a9
Any idea what could be the stem problem?

```python
[E 15:53:03.283 NotebookApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[E 15:53:03.287 NotebookApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 634, in _handle_events
        self._handle_recv()
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 663, in _handle_recv
        self._run_callback(callback, msg)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
Exception in callback BaseAsyncIOLoop._handle_events(45, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(45, 1)>
Traceback (most recent call last):
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
    return callback(self, msg)
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
    super()._on_zmq_reply(stream, msg)
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
    self.write_message(msg, binary=isinstance(msg, bytes))
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
    fut = self._write_frame(True, opcode, message, flags=flags)
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
    return self.stream.write(frame)
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
    self._handle_write()
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/home/aabdalq/miniconda3/envs/mescore/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
    assert 0 < size <= self._size
AssertionError
```

**Comment by kushalkolar** [comment]
This is an issue with jupyter notebook that someone else also ran into, I
would try jupyter lab instead

**Comment by X4ndri** [comment]
Edit: solved by switching to jupyterLab
